# setting up 3 containers namely:
# 1. web - for Django codebase
# 2. postgres_db - for Database operations
# 3. nginx - web server for reverse proxy

version: "3.8"
services:
  web:
    build:
      context: .
    dns:
      - 8.8.8.8  # Google's DNS
    ports:
      - "8000:8000"
    command: ["sh", "./gunicorn.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static/
    depends_on:
      - web

volumes:
  postgres_data: