version: "3.8"
services:
  web:
    build:
      context: .
    dns:
      - 8.8.8.8  # Google's DNS
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=jktechnologies.settings
    command: ["sh", "./gunicorn.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:

