# Generated by Django 4.2.15 on 2024-08-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=200)),
                ('author_details', models.TextField(blank=True, null=True)),
                ('author_country', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('year_published', models.CharField(max_length=4)),
                ('summary', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('author', models.ManyToManyField(related_name='book_author', to='bookmanagement.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
