# Generated by Django 4.2.15 on 2024-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
