# Generated by Django 4.2.15 on 2024-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
